name: "List Molecule scenarios"
description: "List Ansible Molecule scenarios"
inputs:
  subdir:
    description: "If your molecule directory is not at the top of your repository set this path."
    required: true
    default: "."
outputs:
  scenarios:
    description: "List of Molecule scenarios"
runs:
  using: "node12"
  main: "dist/index.js"
